export const Colors = {
  light: {
    background: '#ffffff',
    foreground: '#09090b',
    card: '#ffffff',
    cardForeground: '#09090b',
    border: '#e4e4e7',
    input: '#e4e4e7',
    primary: '#18181b',
    primaryForeground: '#fafafa',
    secondary: '#f4f4f5',
    secondaryForeground: '#18181b',
    muted: '#f4f4f5',
    mutedForeground: '#71717a',
    accent: '#f4f4f5',
    accentForeground: '#18181b',
    destructive: '#ef4444',
    destructiveForeground: '#fafafa',
    ring: '#18181b',
    tabBar: '#ffffff',
    tabBarBorder: '#e4e4e7',
    tabIconActive: '#18181b',
    tabIconInactive: '#a1a1aa',
  },
  dark: {
    background: '#09090b',
    foreground: '#fafafa',
    card: '#09090b',
    cardForeground: '#fafafa',
    border: '#27272a',
    input: '#27272a',
    primary: '#fafafa',
    primaryForeground: '#18181b',
    secondary: '#27272a',
    secondaryForeground: '#fafafa',
    muted: '#27272a',
    mutedForeground: '#a1a1aa',
    accent: '#27272a',
    accentForeground: '#fafafa',
    destructive: '#dc2626',
    destructiveForeground: '#fafafa',
    ring: '#d4d4d8',
    tabBar: '#09090b',
    tabBarBorder: '#27272a',
    tabIconActive: '#fafafa',
    tabIconInactive: '#52525b',
  },
} as const;

export type ThemeColors = (typeof Colors)['light'];
